title: SalesTim Internationalization (i18n)
description: This repository contains resource files used to localize the SalesTim Platform.
theme: jekyll-theme-minimal
logo: https://developers.salestim.com/color.png
show_downloads: false